FROM quay.io/astronomer/astro-runtime:10.1.0-python-3.11

ENV AIRFLOW__WEBSERVER__ALLOW_RAW_HTML_DESCRIPTIONS=True
ENV AIRFLOW__WEBSERVER__NAVBAR_COLOR="#c9eaff"
ENV AIRFLOW__WEBSERVER__NAVBAR_TEXT_COLOR="#37059c" 
ENV AIRFLOW__WEBSERVER__INSTANCE_NAME="2.8 DAGs"