FROM quay.io/astronomer/astro-runtime-dev:10.0.0-alpha8

ENV AIRFLOW__WEBSERVER__ALLOW_RAW_HTML_DESCRIPTIONS=True
ENV AIRFLOW__WEBSERVER__NAVBAR_COLOR="#377030"
ENV AIRFLOW__WEBSERVER__NAVBAR_TEXT_COLOR="#bf0000"